### ISSUE TITLE
Problem with path.py constraint

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.zipexport#40]
The `ftw.book` development installation (Plone 4.3 / Python 2.7) does no longer work because we require an older version of `path.py` for Python 2.6 support (#37).

The problem is that buildout cannot handle that:
```
Version and requirements information containing path.py:
  Requirement of ftw.upgrade: path.py>=6.2
  Requirement of ftw.theming>=1.7.0: path.py
  Requirement of ftw.zipexport: path.py<9.0
  Requirement of ftw.testing: path.py
  Requirement of ftw.builder: path.py
  Requirement of ftw.autofeature: path.py
While:
  Installing omelette.
Error: There is a version conflict.
We already have: path.py 9.0
but ftw.zipexport 1.4.0 requires 'path.py<9.0'.
```
Buildout is not able resolve that and first loads the newest version and then realizes that it does not work.
Because of convenience and because we have to stick to buildout for now I'd like to remove the constraint from the path.py dependency.

**Option 1** (preferred)
Drop Python 2.6 support, eliminating the issue we try to resolve with the constraint.

**Option 2**
Move the version pinning to the `test-plone-4.2.x-py2.6.cfg`, because it does not apply to newer versions.

Opinions?

/cc @Rotonen @phgross

**Comment by lukasgraf** [comment]
🔫  Python2.6 💥

**Comment by Rotonen** [comment]
Assuming nothing in the wild is on 2.6 anymore, the test for that has become unnecessary and may be removed at this point.

**Comment by jone** [comment]
Of 4teamwork's deployments there are more than 300 using `ftw.zipexport`, but only one with `Plone < 4.2` (=Python 2.6 probable). It es expected that when we update `ftw.zipexport`, everything is updated, including the Python version.

Therefore, from 4teamwork's point of view, it is safe to drop Python 2.6 support.
