### ISSUE TITLE
Empty Folders are missing in a ZIP Export

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.zipexport#44]
![bildschirmfoto 2017-08-16 um 16 12 28](https://user-images.githubusercontent.com/557005/29367587-af5920c8-829d-11e7-8278-8aebcaec77bc.png)

![bildschirmfoto 2017-08-16 um 16 12 32](https://user-images.githubusercontent.com/557005/29367588-af5c7eb2-829d-11e7-84b3-3433cfac000b.png)

![bildschirmfoto 2017-08-16 um 16 12 38](https://user-images.githubusercontent.com/557005/29367589-af628c9e-829d-11e7-925a-8080cd5f7163.png)

![bildschirmfoto 2017-08-16 um 16 11 27](https://user-images.githubusercontent.com/557005/29367540-81de4bc8-829d-11e7-81a8-375f77d48022.png)

**Comment by jone** [comment]
This could be a limitation of the ZIP implementation used under the hood.
